site_name: WorldEnder.ai
site_url: https://worldender.ai
theme:
    name: material
    palette:
      primary: red
markdown_extensions:
    - attr_list
    - md_in_html
repo_url: https://github.com/keppy/WorldEnder.ai
