"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/o6p8HKuvKvy
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { SheetTrigger, SheetContent, Sheet } from "@/components/ui/sheet";
import React, { SVGProps } from "react";

export function Landing() {
  const [currentImageIndex, setCurrentImageIndex] = React.useState(0);
  const images = ["/we_hero.png", "/we_hero1.png", "/we_hero2.png"];
  React.useEffect(() => {
    const interval = setInterval(() => {
      setCurrentImageIndex((prevIndex) => (prevIndex + 1) % images.length);
    }, 5000);
    return () => clearInterval(interval);
  }, [images.length]);

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-0">
      <header className="flex justify-between items-center py-8">
        <h1 className="text-5xl font-bold">Welcome to WorldEnder.ai</h1>
        <div className="hidden sm:block">
          <nav className="space-x-4 text-lg">
            <Link className="hover:underline" href="#">
              Table of contents
            </Link>
            <Link className="hover:underline" href="#">
              Roadmap
            </Link>
            <Link className="hover:underline" href="#">
              Get involved
            </Link>
          </nav>
        </div>
        <div className="sm:hidden">
          <Sheet>
            <SheetTrigger asChild>
              <Button className="rounded-full" size="icon" variant="ghost">
                <MenuIcon className="w-6 h-6" />
                <span className="sr-only">Toggle navigation</span>
              </Button>
            </SheetTrigger>
            <SheetContent className="w-64 p-4" side="right">
              <nav className="space-y-2">
                <Link className="block text-lg hover:underline" href="#">
                  Table of contents
                </Link>
                <Link className="block text-lg hover:underline" href="#">
                  Roadmap
                </Link>
                <Link className="block text-lg hover:underline" href="#">
                  Get involved
                </Link>
              </nav>
            </SheetContent>
          </Sheet>
        </div>
      </header>
      <div className="relative">
        <div
          className="w-full h-auto mb-8 transition-opacity duration-500"
          style={{ opacity: currentImageIndex === 0 ? 1 : 0 }}
        >
          <img
            src="/we_hero.png"
            alt="Dystopian cityscape with large red moon"
            className="w-full h-auto"
            height="400"
            style={{
              aspectRatio: "768/400",
              objectFit: "cover",
            }}
            width="768"
          />
        </div>
        <div
          className="w-full h-auto mb-8 absolute top-0 left-0 transition-opacity duration-500"
          style={{ opacity: currentImageIndex === 1 ? 1 : 0 }}
        >
          <img
            src="/we_hero1.png"
            alt="Dystopian cityscape with large red moon"
            className="w-full h-auto"
            height="400"
            style={{
              aspectRatio: "768/400",
              objectFit: "cover",
            }}
            width="768"
          />
        </div>
        <div
          className="w-full h-auto mb-8 absolute top-0 left-0 transition-opacity duration-500"
          style={{ opacity: currentImageIndex === 2 ? 1 : 0 }}
        >
          <img
            src="/we_hero2.png"
            alt="Dystopian cityscape with large red moon"
            className="w-full h-auto"
            height="400"
            style={{
              aspectRatio: "768/400",
              objectFit: "cover",
            }}
            width="768"
          />
        </div>

        <div className="absolute inset-x-0 bottom-0 flex justify-center mb-8">
          <Link
            className="inline-flex h-10 items-center justify-center rounded-md bg-black px-8 text-xl font-medium text-white shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50"
            href="/scenario/new"
          >
            Begin the End...
          </Link>
        </div>
      </div>
      <p className="mb-4">
        A text-adventure RPG about world ending events–and recovering from them!
      </p>
      <p className="mb-8">
        Massively multiplayer, with many language models to choose from.
      </p>
      <h2 className="text-3xl font-bold mb-4">Roadmap</h2>
      <ul className="list-disc pl-5 mb-8">
        <li className="mb-2">
          Fight to keep the world population from reaching 0
        </li>
        <li className="mb-2">Meet other players who occupy other cities</li>
        <li className="mb-2">Customize your AI</li>
      </ul>
      <h2 className="text-3xl font-bold mb-4">Get involved</h2>
      <ul className="list-disc pl-5 mb-8">
        <li className="mb-2">
          Contribute to the open source project WorldEnder.ai on Github
        </li>
        <li className="mb-2">
          Follow
          <Link className="hover:underline" href="#">
            @keppylab_ai
          </Link>
          on X{"\n"}
        </li>
      </ul>
      <p>
        Built by James @
        <Link className="hover:underline" href="#">
          KeppyLab
        </Link>
      </p>
    </div>
  );
}

function MenuIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}
